### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by cjroebuck** [minutebase/ember-inject-script#1]
Thanks for this addon, I'm using it now.. however I had to change the inject statement to:

```
import injectScript from 'ember-inject-script/utils/inject-script';
```

rather than `import injectScript from 'ember-inject-script';` as stated in readme

**Comment by rwjblue** [comment]
@cjroebuck - You have to be using 0.1.1 of ember-cli to be able to import as the README states.

**Comment by rlivsey** [comment]
I should probably add a note to the readme to this effect, although it'll only be an issue until everyone upgrades to 0.1.1+ and due to the awesome speed improvements people should get on that train nice and fast!

**Comment by rlivsey** [comment]
Closing this for now as I think most new users will be on sufficient versions of CLI.
